In [1]:
import numpy as np

In [2]:
r=int(input("Enter the number of rows of matrix: "))

Enter the number of rows of matrix: 2


In [3]:
c=int(input("Enter the number of columns of the matrix: "))

Enter the number of columns of the matrix: 2


In [4]:
m1=np.array([np.array([int(input()) for i in range(c)]) for j in range(r)])

1
3
5
7


In [5]:
print("1st Matrix:\n",m1)

1st Matrix:
 [[1 3]
 [5 7]]


In [6]:
m2=np.array([np.array([int(input()) for i in range(c)]) for j in range(r)]) 

2
4
6
8


In [7]:
print("2nd Matrix:\n",m2)

2nd Matrix:
 [[2 4]
 [6 8]]


In [68]:
dotProduct=np.dot(m1,m2)
print("Dot Product of the 2 Matrics is:\n",dotProduct)

Dot Product of the 2 Matrics is:
 [[20 28]
 [52 76]]


In [75]:
m1T=np.transpose(m1)
print("Transpose of the 1st Matrix is:\n",m1T)

Transpose of the 1st Matrix is:
 [[1 5]
 [3 7]]


In [76]:
m2T=np.transpose(m2)
print("Transpose of the 2nd Matrix is:\n",m2T)

Transpose of the 2nd Matrix is:
 [[2 6]
 [4 8]]


In [71]:
trace1=m1.trace()
print("Sum of diagonal elements of 1st matrix: ",trace1)

Sum of diagonal elements of 1st matrix:  8


In [70]:
trace2=m2.trace()
print("Sum of diagonal elements of 2nd matrix: ",trace2)

Sum of diagonal elements of 2nd matrix:  10


In [73]:
rank1=np.linalg.matrix_rank(m1)
print("The Rank of 1st Matrix: ",rank1)
rank2=np.linalg.matrix_rank(m2)
print("The Rank of 2nd Matrix: ",rank2)

The Rank of 1st Matrix:  2
The Rank of 2nd Matrix:  2


In [74]:
det1=np.linalg.det(m1)
print("The Determinant of 1st Matrix: ", det1)
det2=np.linalg.det(m2)
print("The Determinent of 2nd Matrix: ", det2)

The Determinant of 1st Matrix:  -7.999999999999998
The Determinent of 2nd Matrix:  -8.000000000000002
